# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 和食
japanesefood = Category.create(name: "和食")
japanesefood_1 = japanesefood.children.create(name: "すし・魚料理")
japanesefood_1.children.create([{name: "寿司"},{name: "海鮮丼"},{name: "刺身"},{name: "かに料理"},{name: "ふぐ料理"},{name: "うなぎ"},{name: "魚介・海鮮料理"},{name: "すっぽん料理"},{name: "その他"}])
japanesefood_2 = japanesefood.children.create(name: "和食・日本料理")
japanesefood_2.children.create([{name: "おでん"},{name: "和食"},{name: "日本料理"},{name: "割烹・小料理"},{name: "料亭風"},{name: "懐石料理"},{name: "精進料理"},{name: "おばんざい"},{name: "湯豆腐"},{name: "豆腐料理・湯葉料理"},{name: "釜飯"},{name: "会席料理"},{name: "季節料理"},{name: "くじら料理"},{name: "天ぷら"},{name: "その他"}])
japanesefood_3 = japanesefood.children.create(name: "ラーメン・麺類")
japanesefood_3.children.create([{name: "そば（蕎麦）"},{name: "うどん"},{name: "担々麺"},{name: "刀削麺"},{name: "讃岐うどん"},{name: "カレーうどん"},{name: "ちゃんぽん"},{name: "冷麺"},{name: "油そば"},{name: "B級麺料理"},{name: "ラーメン"},{name: "味噌ラーメン"},{name: "家系ラーメン"},{name: "二郎系ラーメン"},{name: "つけ麺"},{name: "とんこつラーメン"},{name: "塩ラーメン"},{name: "その他"}])
japanesefood_4 = japanesefood.children.create(name: "丼もの・揚げ物")
japanesefood_4.children.create([{name: "丼もの"},{name: "親子丼"},{name: "牛丼"},{name: "天丼"},{name: "カツ丼"},{name: "定食"},{name: "しらす丼"},{name: "穴子丼"},{name: "とんかつ"},{name: "からあげ"},{name: "その他"}])
japanesefood_5 = japanesefood.children.create(name: "お好み焼・粉物")
japanesefood_5.children.create([{name: "たこ焼き"},{name: "明石焼き"},{name: "お好み焼き"},{name: "もんじゃ焼き"},{name: "その他"}])
japanesefood_6 = japanesefood.children.create(name: "郷土料理")
japanesefood_6.children.create([{name: "京料理"},{name: "ひつまぶし"},{name: "ほうとう"},{name: "しっぽく料理"},{name: "北海道料理"},{name: "ご当地グルメ"},{name: "沖縄そば"},{name: "沖縄料理"},{name: "郷土料理"},{name: "九州料理"},{name: "その他"}])
japanesefood_7 = japanesefood.children.create(name: "その他")
japanesefood_7.children.create([{name: "すべて"}])

# アジア料理
asian_cuisine = Category.create(name: "アジア料理")
asian_cuisine_1 = asian_cuisine.children.create(name: "アジア・エスニック")
asian_cuisine_1.children.create([{name: "インドネシア料理"},{name: "ベトナム料理"},{name: "インド料理"},{name: "ネパール料理"},{name: "トルコ料理"},{name: "メキシコ料理"},{name: "シュラスコ"},{name: "シンガポール料理"},{name: "マレーシア料理"},{name: "韓国料理"},{name: "タイ料理"},{name: "パクチー料理"},{name: "インドカレー"},{name: "その他"}])
asian_cuisine_2 = asian_cuisine.children.create(name: "中華")
asian_cuisine_2.children.create([{name: "四川料理"},{name: "広東料理"},{name: "北京料理"},{name: "上海料理・上海蟹"},{name: "台湾料理"},{name: "チャーハン"},{name: "飲茶・点心"},{name: "小龍包"},{name: "餃子"},{name: "その他"}])
asian_cuisine_3 = asian_cuisine.children.create(name: "その他")
asian_cuisine_3.children.create([{name: "すべて"}])

# ヨーロッパ料理
european_cuisine = Category.create(name: "ヨーロッパ料理")
european_cuisine_1 = european_cuisine.children.create(name: "イタリアン")
european_cuisine_1.children.create([{name: "イタリア料理"},{name: "パスタ"},{name: "イタリアンバル"},{name: "ピザ"},{name: "その他"}])
european_cuisine_2 = european_cuisine.children.create(name: "洋食・西洋料理")
european_cuisine_2.children.create([{name: "チーズ料理"},{name: "スープカレー"},{name: "ハヤシライス"},{name: "オムライス"},{name: "スープ"},{name: "シチュー"},{name: "チーズフォンデュ"},{name: "ドイツ料理"},{name: "ロシア料理"},{name: "ハワイ料理"},{name: "洋食"},{name: "スペイン料理"},{name: "ハンバーグ"},{name: "ハンバーガー"},{name: "カレー"},{name: "洋風なおかず"},{name: "その他"}])
european_cuisine_3 = european_cuisine.children.create(name: "フレンチ")
european_cuisine_3.children.create([{name: "ビストロ"},{name: "ジビエ"},{name: "フランス料理"},{name: "その他"}])
european_cuisine_4 = european_cuisine.children.create(name: "アメリカ料理")
european_cuisine_4.children.create([{name: "カリフォルニア料理"},{name: "ケイジャン料理"},{name: "その他"}])
european_cuisine_5 = european_cuisine.children.create(name: "アフリカ料理")
european_cuisine_5.children.create([{name: "エジプト料理"},{name: "モロッコ料理"},{name: "その他"}])
european_cuisine_6 = european_cuisine.children.create(name: "珍しい各国料理")
european_cuisine_6.children.create([{name: "スリランカ料理"},{name: "パキスタン料理"},{name: "アラビア料理"},{name: "オーストラリア料理"},{name: "カリブ料理"},{name: "南米料理"},{name: "無国籍料理"},{name: "その他"}])
european_cuisine_7 = european_cuisine.children.create(name: "その他")
european_cuisine_7.children.create([{name: "すべて"}])

# 肉料理
meat_dish = Category.create(name: "肉料理")
meat_dish_1 = meat_dish.children.create(name: "焼肉・ステーキ")
meat_dish_1.children.create([{name: "牛タン"},{name: "ジンギスカン"},{name: "サムギョプサル"},{name: "鉄板焼き"},{name: "チーズタッカルビ"},{name: "ステーキ"},{name: "焼肉"},{name: "ホルモン"},{name: "その他"}])
meat_dish_2 = meat_dish.children.create(name: "焼鳥・串料理")
meat_dish_2.children.create([{name: "炉端焼き"},{name: "串カツ"},{name: "焼き鳥"},{name: "串揚げ"},{name: "その他"}])
meat_dish_3 = meat_dish.children.create(name: "牛肉")
meat_dish_3.children.create([{name: "牛料理"},{name: "ローストビーフ"},{name: "ビーフステーキ"},{name: "ビーフストロガノフ"},{name: "牛丼"},{name: "チンジャオロース"},{name: "プルコギ"},{name: "ハヤシライス"},{name: "炭火焼き"},{name: "バーベキュー"},{name: "ローストビーフ丼"},{name: "その他"}])
meat_dish_4 = meat_dish.children.create(name: "豚肉")
meat_dish_4.children.create([{name: "豚料理"},{name: "豚の角煮"},{name: "豚の生姜焼き"},{name: "スペアリブ"},{name: "チャーシュー・煮豚"},{name: "酢豚"},{name: "豚バラ肉"},{name: "豚こま切れ肉"},{name: "豚薄切り肉"},{name: "豚かたまり肉"},{name: "その他"}])
meat_dish_5 = meat_dish.children.create(name: "鶏肉")
meat_dish_5.children.create([{name: "鶏料理"},{name: "鶏のから揚げ"},{name: "ローストチキン"},{name: "照り焼きチキン"},{name: "鶏もも肉"},{name: "鶏むね肉"},{name: "鶏ささみ"},{name: "鶏手羽"},{name: "その他"}])
meat_dish_6 = meat_dish.children.create(name: "挽き肉")
meat_dish_6.children.create([{name: "挽き肉料理"},{name: "つくね"},{name: "ハンバーグ"},{name: "餃子・シュウマイ"},{name: "豚まん・肉まん"},{name: "牛挽き肉"},{name: "豚挽き肉"},{name: "あい挽き肉"},{name: "鶏挽き肉"},{name: "ロールキャベツ"},{name: "春巻き"},{name: "その他"}])
meat_dish_7 = meat_dish.children.create(name: "ソーセージ")
meat_dish_7.children.create([{name: "ソーセージを使った料理"},{name: "手作りソーセージ"},{name: "その他"}])
meat_dish_8 = meat_dish.children.create(name: "ハム")
meat_dish_8.children.create([{name: "ハムを使った料理"},{name: "手作り！自家製ハム"},{name: "その他"}])
meat_dish_9 = meat_dish.children.create(name: "ベーコン")
meat_dish_9.children.create([{name: "自家製ベーコン・パンチェッタ"},{name: "ベーコンを使った料理"},{name: "その他"}])
meat_dish_10 = meat_dish.children.create(name: "ハム")
meat_dish_10.children.create([{name: "ハムを使った料理"},{name: "手作り！自家製ハム"},{name: "その他"}])
meat_dish_10 = meat_dish.children.create(name: "モツ")
meat_dish_10.children.create([{name: "レバー"},{name: "ホルモン"},{name: "砂肝"},{name: "モツ鍋・モツ煮"},{name: "その他"}])
meat_dish_11 = meat_dish.children.create(name: "その他")
meat_dish_11.children.create([{name: "ラム肉"},{name: "すべて"}])

# 鍋料理
casserole = Category.create(name: "鍋料理")
casserole_1 = casserole.children.create(name: "鍋")
casserole_1.children.create([{name: "おでん"},{name: "寄せ鍋"},{name: "豆乳鍋"},{name: "みぞれ鍋（雪見鍋）"},{name: "きりたんぽ鍋"},{name: "ちゃんこ鍋"},{name: "水炊き"},{name: "火鍋"},{name: "あんこう鍋 "},{name: "タジン鍋"},{name: "カレー鍋"},{name: "うどんすき"},{name: "もつ鍋"},{name: "蒸し鍋"},{name: "トマト鍋"},{name: "韓国鍋"},{name: "珍しい鍋"},{name: "その他"}])
casserole_2 = casserole.children.create(name: "しゃぶしゃぶ・すき焼き")
casserole_2.children.create([{name: "すき焼き"},{name: "かにしゃぶ"},{name: "しゃぶしゃぶ"},{name: "その他"}])
casserole_3 = casserole.children.create(name: "その他")
casserole_3.children.create([{name: "すべて"}])

# ごはんもの
rice_dishes = Category.create(name: "ごはんもの")
rice_dishes_1 = rice_dishes.children.create(name: "カレー")
rice_dishes_1.children.create([{name: "チキンカレー"},{name: "ポークカレー"},{name: "野菜カレー"},{name: "ビーフカレー"},{name: "タイ風カレー"},{name: "挽肉を使ったカレー"},{name: "インド風カレー"},{name: "ルウから作るカレー"},{name: "ドライカレー"},{name: "スープカレー"},{name: "その他"}])
rice_dishes_2 = rice_dishes.children.create(name: "オムライス")
rice_dishes_2.children.create([{name: "デミ・ブラウンソースオムライス"},{name: "プレーンなオムライス"},{name: "クリームソースオムライス"},{name: "アレンジオムライス"},{name: "その他"}])
rice_dishes_3 = rice_dishes.children.create(name: "寿司")
rice_dishes_3.children.create([{name: "ちらし寿司"},{name: "にぎり寿司・手毬寿司"},{name: "押し寿司"},{name: "巻き寿司"},{name: "いなり寿司"},{name: "寿司飯の作り方"},{name: "お祝い・パーティ寿司"},{name: "その他"}])
rice_dishes_4 = rice_dishes.children.create(name: "どんぶりもの")
rice_dishes_4.children.create([{name: "カツ丼"},{name: "天丼"},{name: "牛丼"},{name: "中華丼"},{name: "親子丼"},{name: "海鮮丼"},{name: "アレンジ丼"},{name: "その他"}])
rice_dishes_5 = rice_dishes.children.create(name: "炒めご飯・チャーハン")
rice_dishes_5.children.create([{name: "あんかけチャーハン"},{name: "海鮮チャーハン"},{name: "お漬物を使ったチャーハン"},{name: "納豆チャーハン"},{name: "アレンジ炒めご飯"},{name: "ナシゴレン"},{name: "その他"}])
rice_dishes_6 = rice_dishes.children.create(name: "炊き込み・まぜご飯")
rice_dishes_6.children.create([{name: "炊き込みご飯"},{name: "まぜご飯"},{name: "おこわ"},{name: "ピラフ"},{name: "パエリヤ"},{name: "ビビンバ"},{name: "その他"}])
rice_dishes_7 = rice_dishes.children.create(name: "リゾット・雑炊類")
rice_dishes_7.children.create([{name: "リゾット"},{name: "雑炊・おじや"},{name: "お粥"},{name: "クッパ"},{name: "その他"}])
rice_dishes_8 = rice_dishes.children.create(name: "アレンジごはん")
rice_dishes_8.children.create([{name: "おにぎり"},{name: "焼きおにぎり"},{name: "ドリア"},{name: "ライスコロッケ"},{name: "お茶漬け"},{name: "その他"}])
rice_dishes_9 = rice_dishes.children.create(name: "その他")
rice_dishes_9.children.create([{name: "すべて"}])

# パスタ・グラタン
pasta_dishes = Category.create(name: "パスタ・グラタン")
pasta_dishes_1 = pasta_dishes.children.create(name: "トマト系パスタ")
pasta_dishes_1.children.create([{name: "ペスカトーレ"},{name: "ミートソース"},{name: "トマトクリーム"},{name: "ボンゴレ・ロッソ"},{name: "ナポリタン"},{name: "アラビアータ"},{name: "トマトソースパスタ"},{name: "その他"}])
pasta_dishes_2 = pasta_dishes.children.create(name: "クリーム系パスタ")
pasta_dishes_2.children.create([{name: "クリームソース"},{name: "カルボナーラ"},{name: "その他"}])
pasta_dishes_3 = pasta_dishes.children.create(name: "オイル・塩系パスタ")
pasta_dishes_3.children.create([{name: "ペペロンチーノ"},{name: "ボンゴレ・ビアンコ"},{name: "アレンジオイル・塩系パスタ"},{name: "その他"}])
pasta_dishes_4 = pasta_dishes.children.create(name: "和風パスタ")
pasta_dishes_4.children.create([{name: "明太子・たらこスパ"},{name: "醤油風味スパ"},{name: "味噌風味スパ"},{name: "梅風味スパ"},{name: "納豆入りスパ"},{name: "その他"}])
pasta_dishes_5 = pasta_dishes.children.create(name: "冷製・アイデアパスタ")
pasta_dishes_5.children.create([{name: "冷製パスタ"},{name: "アイデアパスタ"},{name: "その他"}])
pasta_dishes_6 = pasta_dishes.children.create(name: "グラタン")
pasta_dishes_6.children.create([{name: "かぼちゃのグラタン"},{name: "マカロニグラタン"},{name: "魚介のグラタン"},{name: "チキングラタン"},{name: "ポテトグラタン"},{name: "豆腐グラタン"},{name: "アレンジグラタン"},{name: "その他"}])
pasta_dishes_7 = pasta_dishes.children.create(name: "ラザニア・ラビオリ")
pasta_dishes_7.children.create([{name: "ラザニア"},{name: "ラビオリ"},{name: "アイデアラザニア・ラビオリ"},{name: "その他"}])
pasta_dishes_8 = pasta_dishes.children.create(name: "その他")
pasta_dishes_8.children.create([{name: "ジェノベーゼ"},{name: "スープパスタ"},{name: "ニョッキ"},{name: "手作りパスタに挑戦"},{name: "その他"}])

# 麺
noodle_dishes = Category.create(name: "麺")
noodle_dishes_1 = noodle_dishes.children.create(name: "うどん")
noodle_dishes_1.children.create([{name: "サラダうどん"},{name: "煮込みうどん"},{name: "カレーうどん"},{name: "焼きうどん"},{name: "ほうとう"},{name: "アレンジうどん"},{name: "冷やしうどん"},{name: "その他"}])
noodle_dishes_2 = noodle_dishes.children.create(name: "蕎麦")
noodle_dishes_2.children.create([{name: "あったかい蕎麦"},{name: "冷たい蕎麦"},{name: "蕎麦寿司"},{name: "アレンジ蕎麦"},{name: "その他"}])
noodle_dishes_3 = noodle_dishes.children.create(name: "そうめん")
noodle_dishes_3.children.create([{name: "そうめんチャンプルー"},{name: "にゅうめん"},{name: "アレンジそうめん"},{name: "その他"}])
noodle_dishes_4 = noodle_dishes.children.create(name: "中華麺")
noodle_dishes_4.children.create([{name: "焼きそば"},{name: "ラーメン"},{name: "アレンジ焼きそば"},{name: "ジャージャー麺"},{name: "冷やし中華"},{name: "その他"}])
noodle_dishes_5 = noodle_dishes.children.create(name: "アジアの麺")
noodle_dishes_5.children.create([{name: "ビーフン"},{name: "フォー"},{name: "ビビン麺・冷麺"},{name: "その他"}])
noodle_dishes_6 = noodle_dishes.children.create(name: "手打ち麺に挑戦！")
noodle_dishes_6.children.create([{name: "手打ちうどん"},{name: "手打ち蕎麦・中華麺"},{name: "その他"}])
noodle_dishes_7 = noodle_dishes.children.create(name: "その他")
noodle_dishes_7.children.create([{name: "すべて"}])

# シチュー・スープ・汁物
stew_soup = Category.create(name: "シチュー・スープ・汁物")
stew_soup_1 = stew_soup.children.create(name: "シチュー")
stew_soup_1.children.create([{name: "ビーフシチュー"},{name: "クリームシチュー"},{name: "アレンジシチュー"},{name: "その他"}])
stew_soup_2 = stew_soup.children.create(name: "スープ")
stew_soup_2.children.create([{name: "中華スープ"},{name: "クリームスープ"},{name: "トマトスープ"},{name: "コーンスープ"},{name: "チャウダー"},{name: "ビシソワーズ"},{name: "ガスパチョ"},{name: "ミネストローネ"},{name: "ポタージュ"},{name: "オニオングラタンスープ"},{name: "エスニックなスープ"},{name: "コンソメスープ"},{name: "ラタトゥイユ"},{name: "その他"}])
stew_soup_3 = stew_soup.children.create(name: "汁物")
stew_soup_3.children.create([{name: "お味噌汁"},{name: "お吸い物"},{name: "けんちん汁"},{name: "豚汁"},{name: "その他"}])
stew_soup_4 = stew_soup.children.create(name: "その他")
stew_soup_4.children.create([{name: "すべて"}])

# コロッケ・メンチカツ・たまご・大豆加工品
croquette_soybean = Category.create(name: "コロッケ・メンチカツ・たまご・大豆加工品")
croquette_soybean_1 = croquette_soybean.children.create(name: "コロッケ・メンチカツ")
croquette_soybean_1.children.create([{name: "ポテトコロッケ"},{name: "かぼちゃコロッケ"},{name: "クリームコロッケ"},{name: "さつまいもコロッケ"},{name: "里芋コロッケ"},{name: "おからコロッケ"},{name: "いろんなコロッケ"},{name: "メンチカツ"},{name: "その他"}])
croquette_soybean_2 = croquette_soybean.children.create(name: "たまご")
croquette_soybean_2.children.create([{name: "オムレツ"},{name: "卵焼き"},{name: "温泉たまご・味付たまご"},{name: "茶碗蒸し"},{name: "アレンジたまご料理"},{name: "その他"}])
croquette_soybean_3 = croquette_soybean.children.create(name: "豆腐")
croquette_soybean_3.children.create([{name: "揚げだし豆腐"},{name: "麻婆豆腐"},{name: "豆腐ハンバーグ"},{name: "冷奴"},{name: "ごま豆腐・たまご豆腐"},{name: "おから"},{name: "豆乳"},{name: "高野豆腐"},{name: "納豆"},{name: "湯葉"},{name: "油揚げ"},{name: "厚揚げ"},{name: "アレンジ豆腐料理"},{name: "その他"}])
croquette_soybean_4 = croquette_soybean.children.create(name: "その他")
croquette_soybean_4.children.create([{name: "すべて"}])

# その他の料理
other_dishes = Category.create(name: "その他の料理")
other_dishes_1 = other_dishes.children.create(name: "サラダ")
other_dishes_1.children.create([{name: "和風のサラダ"},{name: "洋風のサラダ"},{name: "中華風のサラダ"},{name: "あったかいサラダ"},{name: "イタリアンサラダ"},{name: "韓国風のサラダ"},{name: "アジアンサラダ"},{name: "マヨネーズ系のサラダ"},{name: "バルサミコ酢を使ったサラダ"},{name: "ナンプラーを使ったサラダ"},{name: "魚介のサラダ"},{name: "お肉を使ったサラダ"},{name: "ツナを使ったサラダ"},{name: "海藻のサラダ"},{name: "トマトのサラダ"},{name: "豆腐のサラダ"},{name: "ゴーヤのサラダ"},{name: "かぼちゃのサラダ"},{name: "ポテトサラダ"},{name: "コールスローサラダ"},{name: "生春巻き"},{name: "その他"}])
other_dishes_2 = other_dishes.children.create(name: "料理")
other_dishes_2.children.create([{name: "創作料理"},{name: "自然食"},{name: "薬膳料理"},{name: "学食系料理"},{name: "弁当のおかず"},{name: "野菜料理"},{name: "にんにく料理"},{name: "その他"}])
other_dishes_3 = other_dishes.children.create(name: "野菜のおかず")
other_dishes_3.children.create([{name: "白菜"},{name: "大根"},{name: "かぶ"},{name: "旬野菜（秋・冬）"},{name: "キャベツ"},{name: "にんじん"},{name: "たまねぎ"},{name: "じゃがいも"},{name: "きのこ"},{name: "豆類"},{name: "脇役野菜・珍しい野菜"},{name: "その他"}])
other_dishes_4 = other_dishes.children.create(name: "魚介のおかず")
other_dishes_4.children.create([{name: "鮭・サーモン"},{name: "いわし"},{name: "さば"},{name: "あじ"},{name: "ぶり"},{name: "さんま"},{name: "鯛"},{name: "マグロ"},{name: "その他"}])
other_dishes_5 = other_dishes.children.create(name: "その他のお魚")
other_dishes_5.children.create([{name: "平目"},{name: "かれい"},{name: "わかさぎ"},{name: "たら"},{name: "さわら"},{name: "きす"},{name: "めばる"},{name: "かじき"},{name: "かつお"},{name: "穴子"},{name: "うなぎ"},{name: "海老"},{name: "イカ"},{name: "たこ"},{name: "その他"}])
other_dishes_6 = other_dishes.children.create(name: "貝類")
other_dishes_6.children.create([{name: "あさり"},{name: "帆立"},{name: "しじみ"},{name: "はまぐり"},{name: "ムール貝"},{name: "牡蠣"},{name: "その他"}])
other_dishes_7 = other_dishes.children.create(name: "その他")
other_dishes_7.children.create([{name: "ツナ缶"},{name: "練り物"},{name: "すべて"}])

# パン
bread = Category.create(name: "パン")
bread_1 = bread.children.create(name: "ハードブレッド・テーブルブレッド")
bread_1.children.create([{name: "フランスパン"},{name: "全粒粉、ライ麦、雑穀パン"},{name: "カンパーニュ"},{name: "バターロール"},{name: "白パン"},{name: "牛乳、生クリーム、卵を使ったパン"},{name: "丸パン"},{name: "その他"}])
bread_2 = bread.children.create(name: "食パン・菓子パン")
bread_2.children.create([{name: "角食パン"},{name: "山型食パン"},{name: "牛乳・生クリーム食パン"},{name: "デニッシュ食パン"},{name: "マーブル生地の食パン"},{name: "アレンジ食パン"},{name: "トヨ型パン・メッシュ型パン"},{name: "あんぱん"},{name: "メロンパン"},{name: "シナモンロール"},{name: "チョコパン・クリームパン"},{name: "菓子パン いろいろ"},{name: "その他"}])
bread_3 = bread.children.create(name: "デニッシュ・クロワッサン・天然酵母")
bread_3.children.create([{name: "クロワッサン"},{name: "デニッシュ"},{name: "自作酵母の作り方"},{name: "自作酵母を使ったパン"},{name: "ホシノ酵母を使ったパン"},{name: "パネトーネマザーを使ったパン"},{name: "その他"}])
bread_4 = bread.children.create(name: "ピザ・野菜・おかず系パン・揚げパン・ドーナツ")
bread_4.children.create([{name: "素材を練りこむパン"},{name: "おかず系のパン"},{name: "ピザ"},{name: "カレーパン"},{name: "揚げパン"},{name: "ドーナツ"},{name: "その他"}])
bread_5 = bread.children.create(name: "蒸しパン・ベーグル作り")
bread_5.children.create([{name: "蒸しパン"},{name: "レンジ蒸しパン"},{name: "ホットケーキミックスを使った蒸しパン"},{name: "ベーグル"},{name: "ベーグルサンド"},{name: "ベーグル使いこなし"},{name: "その他"}])
bread_6 = bread.children.create(name: "世界各国のパン")
bread_6.children.create([{name: "ドイツパン"},{name: "イタリアのパン（フォカッチャ、グリッシーニ）"},{name: "薄焼きパン（ナン・トルティーヤ）"},{name: "ポンデケージョ"},{name: "コーンブレッド"},{name: "その他"}])
bread_7 = bread.children.create(name: "サンドイッチ・ハンバーガー・デコレーションパン")
bread_7.children.create([{name: "ピタパン"},{name: "コッペパン"},{name: "ハンバーガー"},{name: "サンドイッチ"},{name: "デコレーションパン"},{name: "その他"}])
bread_8 = bread.children.create(name: "パンを使って")
bread_8.children.create([{name: "パンプディング"},{name: "ラスク"},{name: "フレンチトースト"},{name: "その他"}])
bread_9 = bread.children.create(name: "その他")
bread_9.children.create([{name: "すべて"}])

# ドリンク・スイーツ
drink_sweets = Category.create(name: "ドリンク・スイーツ")
drink_sweets_1 = drink_sweets.children.create(name: "ドリンク")
drink_sweets_1.children.create([{name: "紅茶"},{name: "コーヒー"},{name: "ココア"},{name: "抹茶ドリンク"},{name: "豆乳ドリンク"},{name: "ヨーグルトドリンク"},{name: "はちみつドリンク"},{name: "チョコレートドリンク"},{name: "しょうがドリンク"},{name: "お酢・サワードリンク"},{name: "ソーダドリンク"},{name: "ミックスジュース"},{name: "シェイク・セーキ"},{name: "スムージー"},{name: "グリーンスムージー"},{name: "チャイ"},{name: "その他"}])
drink_sweets_2 = drink_sweets.children.create(name: "クッキー")
drink_sweets_2.children.create([{name: "型抜きクッキー"},{name: "絞り出しクッキー"},{name: "ショートブレッド"},{name: "和風クッキー"},{name: "ビスコッティ"},{name: "ビスケット"},{name: "マカロン"},{name: "その他"}])
drink_sweets_3 = drink_sweets.children.create(name: "チーズケーキ")
drink_sweets_3.children.create([{name: "ニューヨークチーズケーキ"},{name: "スフレチーズケーキ"},{name: "レアチーズケーキ"},{name: "チーズケーキの色々なアレンジ"},{name: "ベイクドチーズケーキ"},{name: "その他"}])
drink_sweets_4 = drink_sweets.children.create(name: "パウンドケーキ・スポンジケーキ")
drink_sweets_4.children.create([{name: "プレーンなパウンドケーキ"},{name: "色々なパウンドケーキ"},{name: "バナナブレッド"},{name: "クグロフ型を使ったケーキ"},{name: "基本のスポンジ"},{name: "デコレーションケーキ"},{name: "その他"}])
drink_sweets_5 = drink_sweets.children.create(name: "ロールケーキ・シフォンケーキ")
drink_sweets_5.children.create([{name: "プレーンな生地のロールケーキ"},{name: "色々な生地のロールケーキ"},{name: "オーソドックスなシフォン"},{name: "色々なアレンジシフォンケーキ"},{name: "その他"}])
drink_sweets_6 = drink_sweets.children.create(name: "タルト・パイ")
drink_sweets_6.children.create([{name: "タルト台"},{name: "フレッシュタルト"},{name: "ベイクドタルト"},{name: "アップルパイ"},{name: "手作りパイ生地"},{name: "その他のパイ"},{name: "パイシートを使ったお菓子"},{name: "お食事パイ・キッシュ"},{name: "その他"}])
drink_sweets_7 = drink_sweets.children.create(name: "チョコレートのお菓子")
drink_sweets_7.children.create([{name: "チョコレートケーキ"},{name: "ブラウニー"},{name: "生チョコ・トリュフ"},{name: "色々アレンジ チョコレートケーキ"},{name: "フォンダンショコラ"},{name: "チョコレートのクッキー"},{name: "チョコレートのマフィン・スコーン"},{name: "冷たいチョコレートデザート"},{name: "ザッハトルテ"},{name: "その他"}])
drink_sweets_8 = drink_sweets.children.create(name: "マフィン・スコーン")
drink_sweets_8.children.create([{name: "甘くないお食事マフィン"},{name: "色々なマフィン"},{name: "カップケーキ"},{name: "プレーンな型抜きスコーン"},{name: "アメリカンタイプのスコーン"},{name: "色々アレンジスコーン"},{name: "その他"}])
drink_sweets_9 = drink_sweets.children.create(name: "プリン・シュークリーム")
drink_sweets_9.children.create([{name: "カスタードプリン"},{name: "とろけるやわらかプリン"},{name: "色々なアレンジプリン"},{name: "クレームブリュレ"},{name: "シュークリーム・エクレア"},{name: "カスタードクリームの作り方"},{name: "その他"}])
drink_sweets_10 = drink_sweets.children.create(name: "和菓子")
drink_sweets_10.children.create([{name: "お饅頭・大福"},{name: "桜餅・柏餅"},{name: "お団子"},{name: "羊羹"},{name: "手作りあんこ"},{name: "カステラ"},{name: "ぼたもち・おはぎ"},{name: "その他"}])
drink_sweets_11 = drink_sweets.children.create(name: "冷たいお菓子")
drink_sweets_11.children.create([{name: "アイスクリーム"},{name: "ムース・ババロア"},{name: "シャーベット"},{name: "ゼリー・寒天"},{name: "その他"}])
drink_sweets_12 = drink_sweets.children.create(name: "その他のお菓子")
drink_sweets_12.children.create([{name: "ワッフル"},{name: "ヨーグルトのお菓子"},{name: "野菜を使ったお菓子"},{name: "フルーツのお菓子"},{name: "アジアのお菓子"},{name: "クレープ・オムレット"},{name: "パンケーキ"},{name: "バウムクーヘン"},{name: "りんごを使ったお菓子"},{name: "栗を使ったお菓子"},{name: "その他"}])
drink_sweets_13 = drink_sweets.children.create(name: "その他")
drink_sweets_13.children.create([{name: "すべて"}])



